const fs = require('fs');
const path = require('path');

const strings_en = {
    "focus_score": "FOCUS SCORE",
    "focus_score_value": "%1$s%%",
    "productivity": "PRODUCTIVITY",
    "discipline": "DISCIPLINE",
    "level_value": "LEVEL %1$s",
    "calibrated_daily": "Calibrated daily",
    "core_streak": "CORE STREAK",
    "streak_days": "%1$s Days",
    "keep_momentum_high": "Keep momentum high",
    "biological_calibration": "BIOLOGICAL CALIBRATION",
    "cognitive_sleep_reset": "Cognitive Sleep Reset",
    "cognitive_memory_system": "COGNITIVE MEMORY SYSTEM",
    "memory_key_hint": "Memory Key (e.g. style)",
    "memory_content_hint": "Memory Content",
    "teach_second_brain": "Teach your second brain",
    "dynamical_energy_realignment": "DYNAMICAL ENERGY RE-ALIGNMENT",
    "rearranging_cognitive_blocks": "Re-arranging cognitive blocks...",
    "adapt_plan_via_ai": "Adapt Plan via AI",
    "no_agenda_slots": "No agenda slots. Set blocks above.",
    "glow_up_platform": "GLOW-UP PLATFORM",
    "calibrating_roadmap": "Calibrating self-improvement roadmap...",
    "select_category_to_configure": "Select a category above to configure your AI Ascent Roadmap.",
    "self_improvement_milestones": "Self-Improvement Milestones",
    "no_active_milestones": "No active milestones.",
    "inject_agenda_block": "Inject Agenda Block",
    "task_title_hint": "Task Title",
    "energy_required": "Energy required",
    "reject": "Reject",
    "append_block": "Append Block",
    "inject_habit_engine": "Inject Habit Engine",
    "habit_title_hint": "Habit Title",
    "category_theme": "Category Theme",
    "inject": "Inject",
    "streak_days_short": "%1$sd Streak",
    "ambient_field_isolation": "AMBIENT FIELD ISOLATION",
    "system_active": "FOCUSMIND v1.0 • SYSTEM ACTIVE",
    "hero_title": "Your AI-powered\nsecond brain.",
    "hero_subtitle": "FocusMind helps you focus, organize your life, build discipline and achieve your goals with AI.",
    "get_started": "Get Started",
    "try_focusmind_direct": "Try FocusMind Direct",
    "neural_system_log": "Neural System Log",
    "cognitive_memory_desc": "Your second brain persists habits, preferred speech, and user learnings. Update parameters manually below.",
    "voice_link_established": "VOICE LINK ESTABLISHED",
    "ai_inspects_energy": "AI inspects task complexity and aligns agenda elements with your physical energy metric (current: %1$s%%).",
    "optimize_discipline": "Optimize discipline, confidence, dopamine levels, sleep cycles, and physical performance. Generate structured roadmaps.",
    "energy_label": "ENERGY: %1$s",
    "sensory_cognitive_expulsion": "SENSORY COGNITIVE EXPULSION",
    "sleep_hours_value": "%1$.1f Hrs"
};

const ru = {
    ...strings_en,
    "focus_score": "УРОВЕНЬ ФОКУСА",
    "productivity": "ПРОДУКТИВНОСТЬ",
    "discipline": "ДИСЦИПЛИНА",
    "level_value": "УРОВЕНЬ %1$s",
    "calibrated_daily": "Ежедневная калибровка",
    "core_streak": "ОСНОВНАЯ СЕРИЯ",
    "streak_days": "%1$s дней",
    "keep_momentum_high": "Поддерживайте темп",
    "biological_calibration": "БИОЛОГИЧЕСКАЯ КАЛИБРОВКА",
    "cognitive_sleep_reset": "Когнитивный сброс сна",
    "cognitive_memory_system": "СИСТЕМА КОГНИТИВНОЙ ПАМЯТИ",
    "memory_key_hint": "Ключ памяти (например, стиль)",
    "memory_content_hint": "Содержимое памяти",
    "teach_second_brain": "Обучите свой второй мозг",
    "dynamical_energy_realignment": "ДИНАМИЧЕСКОЕ ПЕРЕРАСПРЕДЕЛЕНИЕ ЭНЕРГИИ",
    "rearranging_cognitive_blocks": "Перестановка когнитивных блоков...",
    "adapt_plan_via_ai": "Адаптировать план через ИИ",
    "no_agenda_slots": "Нет блоков повестки дня. Создайте их выше.",
    "glow_up_platform": "ПЛАТФОРМА GLOW-UP",
    "calibrating_roadmap": "Калибровка дорожной карты саморазвития...",
    "select_category_to_configure": "Выберите категорию выше, чтобы настроить вашу дорожную карту развития ИИ.",
    "self_improvement_milestones": "Вехи самосовершенствования",
    "no_active_milestones": "Нет активных вех.",
    "inject_agenda_block": "Добавить блок повестки дня",
    "task_title_hint": "Название задачи",
    "energy_required": "Требуемая энергия",
    "reject": "Отклонить",
    "append_block": "Добавить блок",
    "inject_habit_engine": "Внедрить механизм привычки",
    "habit_title_hint": "Название привычки",
    "category_theme": "Тема категории",
    "inject": "Внедрить",
    "streak_days_short": "Серия %1$sд",
    "ambient_field_isolation": "ИЗОЛЯЦИЯ ОРКУЖАЮЩЕГО ПОЛЯ",
    "system_active": "FOCUSMIND v1.0 • СИСТЕМА АКТИВНА",
    "hero_title": "Ваш второй мозг\nна базе ИИ.",
    "hero_subtitle": "FocusMind помогает сосредоточиться, организовать жизнь, выработать дисциплину и достигать целей с ИИ.",
    "get_started": "Начать",
    "try_focusmind_direct": "Попробовать FocusMind Direct",
    "neural_system_log": "Журнал нейронной системы",
    "cognitive_memory_desc": "Ваш второй мозг сохраняет привычки, предпочтения в общении и навыки. Обновите параметры ниже.",
    "voice_link_established": "ГОЛОСОВАЯ СВЯЗЬ УСТАНОВЛЕНА",
    "ai_inspects_energy": "ИИ анализирует сложность задач и сопоставляет их с вашей физической энергией (сейчас: %1$s%%).",
    "optimize_discipline": "Улучшайте дисциплину, уверенность, уровень дофамина, циклы сна и продуктивность.",
    "energy_label": "ЭНЕРГИЯ: %1$s",
    "sensory_cognitive_expulsion": "СЕНСОРНЫЙ КОГНИТИВНЫЙ ВЫБРОС",
    "sleep_hours_value": "%1$.1f ч"
};

const es = {
    ...strings_en,
    "focus_score": "PUNTUACIÓN DE ENFOQUE",
    "productivity": "PRODUCTIVIDAD",
    "discipline": "DISCIPLINA",
    "level_value": "NIVEL %1$s",
    "calibrated_daily": "Calibrado diariamente",
    "core_streak": "RACHA PRINCIPAL",
    "streak_days": "%1$s Días",
    "keep_momentum_high": "Mantenga el impulso",
    "biological_calibration": "CALIBRACIÓN BIOLÓGICA",
    "cognitive_sleep_reset": "Restablecimiento cognitivo del sueño",
    "cognitive_memory_system": "SISTEMA DE MEMORIA COGNITIVA",
    "memory_key_hint": "Clave de memoria (ej. estilo)",
    "memory_content_hint": "Contenido de memoria",
    "teach_second_brain": "Enseña a tu segundo cerebro",
    "dynamical_energy_realignment": "REALINEACIÓN DE ENERGÍA DINÁMICA",
    "rearranging_cognitive_blocks": "Reorganizando bloques cognitivos...",
    "adapt_plan_via_ai": "Adaptar plan vía IA",
    "no_agenda_slots": "No hay bloques de agenda. Configúrelos arriba.",
    "glow_up_platform": "PLATAFORMA GLOW-UP",
    "calibrating_roadmap": "Calibrando hoja de ruta de mejora personal...",
    "select_category_to_configure": "Seleccione una categoría arriba para configurar su hoja de ruta de ascenso de IA.",
    "self_improvement_milestones": "Hitos de mejora personal",
    "no_active_milestones": "No hay hitos activos.",
    "inject_agenda_block": "Inyectar bloque de agenda",
    "task_title_hint": "Título de la tarea",
    "energy_required": "Energía requerida",
    "reject": "Rechazar",
    "append_block": "Agregar bloque",
    "inject_habit_engine": "Inyectar motor de hábitos",
    "habit_title_hint": "Título del hábito",
    "category_theme": "Tema de la categoría",
    "inject": "Inyectar",
    "streak_days_short": "Racha %1$sd",
    "ambient_field_isolation": "AISLAMIENTO DE CAMPO AMBIENTAL",
    "system_active": "FOCUSMIND v1.0 • SISTEMA ACTIVO",
    "hero_title": "Tu segundo cerebro\nimpulsado por IA.",
    "hero_subtitle": "FocusMind te ayuda a concentrarte, organizar tu vida, desarrollar disciplina y lograr tus objetivos con IA.",
    "get_started": "Empezar",
    "try_focusmind_direct": "Probar FocusMind Direct",
    "neural_system_log": "Registro del sistema neuronal",
    "cognitive_memory_desc": "Tu segundo cerebro conserva hábitos, habla preferida y aprendizajes del usuario.",
    "voice_link_established": "VÍNCULO DE VOZ ESTABLECIDO",
    "ai_inspects_energy": "La IA inspecciona la complejidad de la tarea y alinea los elementos de la agenda con tu energía (actual: %1$s%%).",
    "optimize_discipline": "Optimiza disciplina, confianza, niveles de dopamina, ciclos de sueño y rendimiento físico.",
    "energy_label": "ENERGÍA: %1$s",
    "sensory_cognitive_expulsion": "EXPULSIÓN COGNITIVA SENSORIAL",
    "sleep_hours_value": "%1$.1f Hrs"
};

const zh = {
    ...strings_en,
    "focus_score": "专注力得分",
    "productivity": "生产力",
    "discipline": "纪律",
    "level_value": "等级 %1$s",
    "calibrated_daily": "每日校准",
    "core_streak": "核心连击",
    "streak_days": "%1$s 天",
    "keep_momentum_high": "保持动力",
    "biological_calibration": "生物校准",
    "cognitive_sleep_reset": "认知睡眠重置",
    "cognitive_memory_system": "认知记忆系统",
    "memory_key_hint": "记忆键 (如. 风格)",
    "memory_content_hint": "记忆内容",
    "teach_second_brain": "教导你的第二大脑",
    "dynamical_energy_realignment": "动态能量重新分配",
    "rearranging_cognitive_blocks": "重新排列认知块...",
    "adapt_plan_via_ai": "通过 AI 调整计划",
    "no_agenda_slots": "没有议程空档。在上方设置。",
    "glow_up_platform": "成长平台",
    "calibrating_roadmap": "正在校准自我提升路线图...",
    "select_category_to_configure": "在上方选择一个类别以配置您的 AI 晋升路线图.",
    "self_improvement_milestones": "自我提升里程碑",
    "no_active_milestones": "没有活动里程碑。",
    "inject_agenda_block": "注入议程块",
    "task_title_hint": "任务标题",
    "energy_required": "所需能量",
    "reject": "拒绝",
    "append_block": "追加块",
    "inject_habit_engine": "注入习惯引擎",
    "habit_title_hint": "习惯标题",
    "category_theme": "分类主题",
    "inject": "注入",
    "streak_days_short": "%1$s天 连击",
    "ambient_field_isolation": "环境声场隔离",
    "system_active": "FOCUSMIND v1.0 • 系统活跃",
    "hero_title": "你的 AI 驱动\n第二大脑。",
    "hero_subtitle": "FocusMind 帮助您集中注意力，安排生活，建立纪律并实现目标。",
    "get_started": "开始吧",
    "try_focusmind_direct": "尝试 FocusMind 直连",
    "neural_system_log": "神经系统日志",
    "cognitive_memory_desc": "你的第二大脑持续保存习惯、偏好的对话和用户学习。",
    "voice_link_established": "已建立语音连接",
    "ai_inspects_energy": "AI 检查任务复杂性并将议程元素与你的身体能量指标对齐 (当前: %1$s%%).",
    "optimize_discipline": "优化纪律性、自信心、多巴胺水平、睡眠周期和身体表现。",
    "energy_label": "能量: %1$s",
    "sensory_cognitive_expulsion": "感官认知驱逐",
    "sleep_hours_value": "%1$.1f 小时"
};

const ar = {
    ...strings_en,
    "focus_score": "درجة التركيز",
    "productivity": "الإنتاجية",
    "discipline": "الانضباط",
    "level_value": "المستوى %1$s",
    "calibrated_daily": "معايرة يومية",
    "core_streak": "الخط الأساسي",
    "streak_days": "%1$s أيام",
    "keep_momentum_high": "حافظ على الزخم عالياً",
    "biological_calibration": "المعايرة البيولوجية",
    "cognitive_sleep_reset": "إعادة ضبط النوم المعرفي",
    "cognitive_memory_system": "نظام الذاكرة المعرفي",
    "memory_key_hint": "مفتاح الذاكرة (مثل الأسلوب)",
    "memory_content_hint": "محتوى الذاكرة",
    "teach_second_brain": "علم دماغك الثاني",
    "dynamical_energy_realignment": "إعادة التنظيم الديناميكي للطاقة",
    "rearranging_cognitive_blocks": "إعادة ترتيب الكتل المعرفية...",
    "adapt_plan_via_ai": "تكييف الخطة عبر الذكاء الاصطناعي",
    "no_agenda_slots": "لا توجد كتل في الأجندة. قم بتعيين الكتل في الأعلى.",
    "glow_up_platform": "منصة التوهج",
    "calibrating_roadmap": "معايرة خارطة طريق تطوير الذات...",
    "select_category_to_configure": "حدد فئة أعلاه لتهيئة خارطة طريق ارتقاء الذكاء الاصطناعي الخاصة بك.",
    "self_improvement_milestones": "معالم تطوير الذات",
    "no_active_milestones": "لا توجد معالم نشطة.",
    "inject_agenda_block": "إدراج كتلة أجندة",
    "task_title_hint": "عنوان المهمة",
    "energy_required": "الطاقة المطلوبة",
    "reject": "رفض",
    "append_block": "إضافة كتلة",
    "inject_habit_engine": "إدراج محرك العادات",
    "habit_title_hint": "عنوان العادة",
    "category_theme": "موضوع الفئة",
    "inject": "إدراج",
    "streak_days_short": "سلسلة %1$sd",
    "ambient_field_isolation": "عزل المجال المحيط",
    "system_active": "FOCUSMIND v1.0 • النظام نشط",
    "hero_title": "دماغك الثاني\nالمدعوم بالذكاء الاصطناعي.",
    "hero_subtitle": "يساعدك FocusMind على التركيز وتنظيم حياتك وبناء الانضباط وتحقيق أهدافك من خلال الذكاء الاصطناعي.",
    "get_started": "ابدأ",
    "try_focusmind_direct": "جرب FocusMind مباشرة",
    "neural_system_log": "سجل النظام العصبي",
    "cognitive_memory_desc": "يحتفظ دماغك الثاني بالعادات وأنماط الحديث المفضلة والمتعلمات الخاصة بالمستخدم. قم بتحديث المعلمات يدويًا بالأسفل.",
    "voice_link_established": "تم إنشاء ارتباط صوتي",
    "ai_inspects_energy": "يقوم الذكاء الاصطناعي بفحص تعقيد المهمة ومواءمة عناصر الأجندة مع مقياس الطاقة المادية الخاص بك (الحالي: %1$s%%).",
    "optimize_discipline": "تحسين الانضباط والثقة ومستويات الدوبامين ودورات النوم والأداء البدني.",
    "energy_label": "الطاقة: %1$s",
    "sensory_cognitive_expulsion": "طرد الإدراك الحسي",
    "sleep_hours_value": "%1$.1f ساعة"
};

const langs = [
    { code: '', data: strings_en },
    { code: '-ru', data: ru },
    { code: '-es', data: es },
    { code: '-zh', data: zh },
    { code: '-ar', data: ar }
];

langs.forEach(lang => {
    let filePath = `app/src/main/res/values${lang.code}/strings.xml`;
    if (!fs.existsSync(filePath)) {
        return;
    }
    let content = fs.readFileSync(filePath, 'utf8');
    for (const [key, value] of Object.entries(lang.data)) {
        let name = key;
        let p = new RegExp(`name="${name}"`, 'g');
        if (!p.test(content)) {
            // escape
            let escapedVal = value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/'/g, "\\'").replace(/"/g, '&quot;').replace(/\n/g, '\\n');
            let insertion = `    <string name="${name}">${escapedVal}</string>\n</resources>`;
            content = content.replace("</resources>", insertion);
        }
    }
    fs.writeFileSync(filePath, content, 'utf8');
});
console.log("Updated XML resources successfully");
